service: aws-python-flask-dynamodb-api

frameworkVersion: '2'

custom:
  tableName: 'users-table-${self:provider.stage}'
  wsgi:
    app: app.app

  pythonRequirements:
    pythonBin: python3

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-offline

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}

# iamRoleStatements: # permissions for all of your functions can be set here
# - Effect: Allow
#   Action: # Gives permission to DynamoDB tables in a specific region
#       - dynamodb:DescribeTable
#       - dynamodb:Query
#       - dynamodb:Scan
#       - dynamodb:GetItem
#       - dynamodb:PutItem
#       - dynamodb:UpdateItem
#       - dynamodb:DeleteItem
#   Resource:
#       - 'arn:aws:dynamodb:us-east-1:516841194344/Contests